%mex -lMadlib create_thread.cpp 
mex  -g -v -compatibleArrayDims -I'C:\Program Files\MySQL\MySQL Server 5.6\include' ...
    '-LC:\Program Files (x86)\National Instruments\Shared\ExternalCompilerSupport\C\lib64\msvc' ...
    '-LC:\Users\lab\Documents\MATLAB\ImageScan_in_development\ImageScan_v2019_1219setup\AFMScan\mDAC_C\FreeImage\Dist\x64' ...
    '-LC:\Program Files\Mad City Labs\NanoDrive'...
    '-LC:\Program Files\MATLAB\R2021a\extern\lib\win64' ...
    -lNIDAQmx -llibmysql -lFreeImage -lMadlib -llibMatlabCppSharedLib mDAC.cpp Serial.cpp DAC.cpp scan.cpp bestfit.cpp

copyfile('mDAC.mexw64','..\')